[package]
name = "rings"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
diameter = "0.7.1"
rdkafka = "0.36.2"
env_logger = "0.11.5"
tokio = "1.40.0"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"]}
is_empty = "0.2.0"
